INSERT INTO CP."@EXX_ESTATUS"  VALUES('01','Libres','');
INSERT INTO CP."@EXX_ESTATUS"  VALUES('02','Asignadas','');
INSERT INTO CP."@EXX_ESTATUS"  VALUES('03','Reservadas','');
INSERT INTO CP."@EXX_ESTATUS"  VALUES('04','Formalizadas','');
INSERT INTO CP."@EXX_ESTATUS"  VALUES('05','Protocolizadas','');
INSERT INTO CP."@EXX_ESTATUS"  VALUES('06','Entregadas','');
INSERT INTO CP."@EXX_ESTATUS"  VALUES('07','Alquiladas','');
INSERT INTO CP."@EXX_ESTATUS"  VALUES('08','Hipotecadas','');